#!/bin/bash
#
# Start script for mysql
#
# Some overwriteable vars
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)}
MYSQL_DATA_FOLDER=${MYSQL_DATA_FOLDER:-/var/lib/mysql/}
# Do simple check if databases already exists
# in data folder by checking if folder mysql
# exists in the location of MYSQL_DATA_FOLDER
# this should representing the mysql table
if [[ ! -d "${MYSQL_DATA_FOLDER}mysql" ]]; then
    # Create all dafult databases
    if [[ -f "/root/.my.cnf" ]] ; then
        /usr/bin/mysql_install_db --defaults-file=/root/.my.cnf
    else
        /usr/bin/mysql_install_db
    fi
fi

# Check if root password is changed
# by schecking if file exists, if
# not it will try to create and set
# new password for root use
if [[ ! -f "/root/.my.cnf" ]]; then
    # Start mysql in background
    /usr/bin/mysqld_safe &
    # Wait for database to be ups
    /usr/bin/mysqladmin --silent --wait=30 ping || exit 40
    (cat <<EOF
USE mysql;
UPDATE user SET password=PASSWORD("${MYSQL_ROOT_PASSWORD}") where User="root";
GRANT ALL PRIVILEGES ON *.* TO "root"@"%" WITH GRANT OPTION;
FLUSH PRIVILEGES;
EOF
    ) | mysql -v
    # Make config file
    ( cat <<EOF
[client]
user = root
password = ${MYSQL_ROOT_PASSWORD}
EOF
    ) > /root/.my.cnf

    /usr/bin/mysqladmin shutdown
fi

/usr/bin/mysqld_safe